/*
Emby Server API

Explore the Emby Server API

API version: 4.1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TasksTaskInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TasksTaskInfo{}

// TasksTaskInfo struct for TasksTaskInfo
type TasksTaskInfo struct {
	Name *string `json:"Name,omitempty"`
	State *string `json:"State,omitempty"`
	CurrentProgressPercentage NullableFloat64 `json:"CurrentProgressPercentage,omitempty"`
	Id *string `json:"Id,omitempty"`
	LastExecutionResult *TasksTaskResult `json:"LastExecutionResult,omitempty"`
	Triggers []TasksTaskTriggerInfo `json:"Triggers,omitempty"`
	Description *string `json:"Description,omitempty"`
	Category *string `json:"Category,omitempty"`
	IsHidden *bool `json:"IsHidden,omitempty"`
	Key *string `json:"Key,omitempty"`
}

// NewTasksTaskInfo instantiates a new TasksTaskInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTasksTaskInfo() *TasksTaskInfo {
	this := TasksTaskInfo{}
	return &this
}

// NewTasksTaskInfoWithDefaults instantiates a new TasksTaskInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTasksTaskInfoWithDefaults() *TasksTaskInfo {
	this := TasksTaskInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TasksTaskInfo) SetName(v string) {
	o.Name = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *TasksTaskInfo) SetState(v string) {
	o.State = &v
}

// GetCurrentProgressPercentage returns the CurrentProgressPercentage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TasksTaskInfo) GetCurrentProgressPercentage() float64 {
	if o == nil || IsNil(o.CurrentProgressPercentage.Get()) {
		var ret float64
		return ret
	}
	return *o.CurrentProgressPercentage.Get()
}

// GetCurrentProgressPercentageOk returns a tuple with the CurrentProgressPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksTaskInfo) GetCurrentProgressPercentageOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentProgressPercentage.Get(), o.CurrentProgressPercentage.IsSet()
}

// HasCurrentProgressPercentage returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasCurrentProgressPercentage() bool {
	if o != nil && o.CurrentProgressPercentage.IsSet() {
		return true
	}

	return false
}

// SetCurrentProgressPercentage gets a reference to the given NullableFloat64 and assigns it to the CurrentProgressPercentage field.
func (o *TasksTaskInfo) SetCurrentProgressPercentage(v float64) {
	o.CurrentProgressPercentage.Set(&v)
}
// SetCurrentProgressPercentageNil sets the value for CurrentProgressPercentage to be an explicit nil
func (o *TasksTaskInfo) SetCurrentProgressPercentageNil() {
	o.CurrentProgressPercentage.Set(nil)
}

// UnsetCurrentProgressPercentage ensures that no value is present for CurrentProgressPercentage, not even an explicit nil
func (o *TasksTaskInfo) UnsetCurrentProgressPercentage() {
	o.CurrentProgressPercentage.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TasksTaskInfo) SetId(v string) {
	o.Id = &v
}

// GetLastExecutionResult returns the LastExecutionResult field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetLastExecutionResult() TasksTaskResult {
	if o == nil || IsNil(o.LastExecutionResult) {
		var ret TasksTaskResult
		return ret
	}
	return *o.LastExecutionResult
}

// GetLastExecutionResultOk returns a tuple with the LastExecutionResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetLastExecutionResultOk() (*TasksTaskResult, bool) {
	if o == nil || IsNil(o.LastExecutionResult) {
		return nil, false
	}
	return o.LastExecutionResult, true
}

// HasLastExecutionResult returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasLastExecutionResult() bool {
	if o != nil && !IsNil(o.LastExecutionResult) {
		return true
	}

	return false
}

// SetLastExecutionResult gets a reference to the given TasksTaskResult and assigns it to the LastExecutionResult field.
func (o *TasksTaskInfo) SetLastExecutionResult(v TasksTaskResult) {
	o.LastExecutionResult = &v
}

// GetTriggers returns the Triggers field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetTriggers() []TasksTaskTriggerInfo {
	if o == nil || IsNil(o.Triggers) {
		var ret []TasksTaskTriggerInfo
		return ret
	}
	return o.Triggers
}

// GetTriggersOk returns a tuple with the Triggers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetTriggersOk() ([]TasksTaskTriggerInfo, bool) {
	if o == nil || IsNil(o.Triggers) {
		return nil, false
	}
	return o.Triggers, true
}

// HasTriggers returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasTriggers() bool {
	if o != nil && !IsNil(o.Triggers) {
		return true
	}

	return false
}

// SetTriggers gets a reference to the given []TasksTaskTriggerInfo and assigns it to the Triggers field.
func (o *TasksTaskInfo) SetTriggers(v []TasksTaskTriggerInfo) {
	o.Triggers = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TasksTaskInfo) SetDescription(v string) {
	o.Description = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *TasksTaskInfo) SetCategory(v string) {
	o.Category = &v
}

// GetIsHidden returns the IsHidden field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetIsHidden() bool {
	if o == nil || IsNil(o.IsHidden) {
		var ret bool
		return ret
	}
	return *o.IsHidden
}

// GetIsHiddenOk returns a tuple with the IsHidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetIsHiddenOk() (*bool, bool) {
	if o == nil || IsNil(o.IsHidden) {
		return nil, false
	}
	return o.IsHidden, true
}

// HasIsHidden returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasIsHidden() bool {
	if o != nil && !IsNil(o.IsHidden) {
		return true
	}

	return false
}

// SetIsHidden gets a reference to the given bool and assigns it to the IsHidden field.
func (o *TasksTaskInfo) SetIsHidden(v bool) {
	o.IsHidden = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *TasksTaskInfo) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TasksTaskInfo) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *TasksTaskInfo) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *TasksTaskInfo) SetKey(v string) {
	o.Key = &v
}

func (o TasksTaskInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TasksTaskInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.State) {
		toSerialize["State"] = o.State
	}
	if o.CurrentProgressPercentage.IsSet() {
		toSerialize["CurrentProgressPercentage"] = o.CurrentProgressPercentage.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.LastExecutionResult) {
		toSerialize["LastExecutionResult"] = o.LastExecutionResult
	}
	if !IsNil(o.Triggers) {
		toSerialize["Triggers"] = o.Triggers
	}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !IsNil(o.Category) {
		toSerialize["Category"] = o.Category
	}
	if !IsNil(o.IsHidden) {
		toSerialize["IsHidden"] = o.IsHidden
	}
	if !IsNil(o.Key) {
		toSerialize["Key"] = o.Key
	}
	return toSerialize, nil
}

type NullableTasksTaskInfo struct {
	value *TasksTaskInfo
	isSet bool
}

func (v NullableTasksTaskInfo) Get() *TasksTaskInfo {
	return v.value
}

func (v *NullableTasksTaskInfo) Set(val *TasksTaskInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTasksTaskInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTasksTaskInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTasksTaskInfo(val *TasksTaskInfo) *NullableTasksTaskInfo {
	return &NullableTasksTaskInfo{value: val, isSet: true}
}

func (v NullableTasksTaskInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTasksTaskInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


