/*
Emby Server API

Explore the Emby Server API

API version: 4.1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ExternalIdInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalIdInfo{}

// ExternalIdInfo struct for ExternalIdInfo
type ExternalIdInfo struct {
	Name *string `json:"Name,omitempty"`
	Key *string `json:"Key,omitempty"`
	UrlFormatString *string `json:"UrlFormatString,omitempty"`
}

// NewExternalIdInfo instantiates a new ExternalIdInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalIdInfo() *ExternalIdInfo {
	this := ExternalIdInfo{}
	return &this
}

// NewExternalIdInfoWithDefaults instantiates a new ExternalIdInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalIdInfoWithDefaults() *ExternalIdInfo {
	this := ExternalIdInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ExternalIdInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalIdInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ExternalIdInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ExternalIdInfo) SetName(v string) {
	o.Name = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ExternalIdInfo) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalIdInfo) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ExternalIdInfo) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ExternalIdInfo) SetKey(v string) {
	o.Key = &v
}

// GetUrlFormatString returns the UrlFormatString field value if set, zero value otherwise.
func (o *ExternalIdInfo) GetUrlFormatString() string {
	if o == nil || IsNil(o.UrlFormatString) {
		var ret string
		return ret
	}
	return *o.UrlFormatString
}

// GetUrlFormatStringOk returns a tuple with the UrlFormatString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalIdInfo) GetUrlFormatStringOk() (*string, bool) {
	if o == nil || IsNil(o.UrlFormatString) {
		return nil, false
	}
	return o.UrlFormatString, true
}

// HasUrlFormatString returns a boolean if a field has been set.
func (o *ExternalIdInfo) HasUrlFormatString() bool {
	if o != nil && !IsNil(o.UrlFormatString) {
		return true
	}

	return false
}

// SetUrlFormatString gets a reference to the given string and assigns it to the UrlFormatString field.
func (o *ExternalIdInfo) SetUrlFormatString(v string) {
	o.UrlFormatString = &v
}

func (o ExternalIdInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalIdInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Key) {
		toSerialize["Key"] = o.Key
	}
	if !IsNil(o.UrlFormatString) {
		toSerialize["UrlFormatString"] = o.UrlFormatString
	}
	return toSerialize, nil
}

type NullableExternalIdInfo struct {
	value *ExternalIdInfo
	isSet bool
}

func (v NullableExternalIdInfo) Get() *ExternalIdInfo {
	return v.value
}

func (v *NullableExternalIdInfo) Set(val *ExternalIdInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalIdInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalIdInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalIdInfo(val *ExternalIdInfo) *NullableExternalIdInfo {
	return &NullableExternalIdInfo{value: val, isSet: true}
}

func (v NullableExternalIdInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalIdInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


