/*
Emby Server API

Explore the Emby Server API

API version: 4.1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the DlnaDirectPlayProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DlnaDirectPlayProfile{}

// DlnaDirectPlayProfile struct for DlnaDirectPlayProfile
type DlnaDirectPlayProfile struct {
	Container *string `json:"Container,omitempty"`
	AudioCodec *string `json:"AudioCodec,omitempty"`
	VideoCodec *string `json:"VideoCodec,omitempty"`
	Type *string `json:"Type,omitempty"`
}

// NewDlnaDirectPlayProfile instantiates a new DlnaDirectPlayProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDlnaDirectPlayProfile() *DlnaDirectPlayProfile {
	this := DlnaDirectPlayProfile{}
	return &this
}

// NewDlnaDirectPlayProfileWithDefaults instantiates a new DlnaDirectPlayProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDlnaDirectPlayProfileWithDefaults() *DlnaDirectPlayProfile {
	this := DlnaDirectPlayProfile{}
	return &this
}

// GetContainer returns the Container field value if set, zero value otherwise.
func (o *DlnaDirectPlayProfile) GetContainer() string {
	if o == nil || IsNil(o.Container) {
		var ret string
		return ret
	}
	return *o.Container
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DlnaDirectPlayProfile) GetContainerOk() (*string, bool) {
	if o == nil || IsNil(o.Container) {
		return nil, false
	}
	return o.Container, true
}

// HasContainer returns a boolean if a field has been set.
func (o *DlnaDirectPlayProfile) HasContainer() bool {
	if o != nil && !IsNil(o.Container) {
		return true
	}

	return false
}

// SetContainer gets a reference to the given string and assigns it to the Container field.
func (o *DlnaDirectPlayProfile) SetContainer(v string) {
	o.Container = &v
}

// GetAudioCodec returns the AudioCodec field value if set, zero value otherwise.
func (o *DlnaDirectPlayProfile) GetAudioCodec() string {
	if o == nil || IsNil(o.AudioCodec) {
		var ret string
		return ret
	}
	return *o.AudioCodec
}

// GetAudioCodecOk returns a tuple with the AudioCodec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DlnaDirectPlayProfile) GetAudioCodecOk() (*string, bool) {
	if o == nil || IsNil(o.AudioCodec) {
		return nil, false
	}
	return o.AudioCodec, true
}

// HasAudioCodec returns a boolean if a field has been set.
func (o *DlnaDirectPlayProfile) HasAudioCodec() bool {
	if o != nil && !IsNil(o.AudioCodec) {
		return true
	}

	return false
}

// SetAudioCodec gets a reference to the given string and assigns it to the AudioCodec field.
func (o *DlnaDirectPlayProfile) SetAudioCodec(v string) {
	o.AudioCodec = &v
}

// GetVideoCodec returns the VideoCodec field value if set, zero value otherwise.
func (o *DlnaDirectPlayProfile) GetVideoCodec() string {
	if o == nil || IsNil(o.VideoCodec) {
		var ret string
		return ret
	}
	return *o.VideoCodec
}

// GetVideoCodecOk returns a tuple with the VideoCodec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DlnaDirectPlayProfile) GetVideoCodecOk() (*string, bool) {
	if o == nil || IsNil(o.VideoCodec) {
		return nil, false
	}
	return o.VideoCodec, true
}

// HasVideoCodec returns a boolean if a field has been set.
func (o *DlnaDirectPlayProfile) HasVideoCodec() bool {
	if o != nil && !IsNil(o.VideoCodec) {
		return true
	}

	return false
}

// SetVideoCodec gets a reference to the given string and assigns it to the VideoCodec field.
func (o *DlnaDirectPlayProfile) SetVideoCodec(v string) {
	o.VideoCodec = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DlnaDirectPlayProfile) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DlnaDirectPlayProfile) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DlnaDirectPlayProfile) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DlnaDirectPlayProfile) SetType(v string) {
	o.Type = &v
}

func (o DlnaDirectPlayProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DlnaDirectPlayProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Container) {
		toSerialize["Container"] = o.Container
	}
	if !IsNil(o.AudioCodec) {
		toSerialize["AudioCodec"] = o.AudioCodec
	}
	if !IsNil(o.VideoCodec) {
		toSerialize["VideoCodec"] = o.VideoCodec
	}
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	return toSerialize, nil
}

type NullableDlnaDirectPlayProfile struct {
	value *DlnaDirectPlayProfile
	isSet bool
}

func (v NullableDlnaDirectPlayProfile) Get() *DlnaDirectPlayProfile {
	return v.value
}

func (v *NullableDlnaDirectPlayProfile) Set(val *DlnaDirectPlayProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableDlnaDirectPlayProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableDlnaDirectPlayProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDlnaDirectPlayProfile(val *DlnaDirectPlayProfile) *NullableDlnaDirectPlayProfile {
	return &NullableDlnaDirectPlayProfile{value: val, isSet: true}
}

func (v NullableDlnaDirectPlayProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDlnaDirectPlayProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


