/*
Emby Server API

Explore the Emby Server API

API version: 4.1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the EmbyReportsApiModelReportItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbyReportsApiModelReportItem{}

// EmbyReportsApiModelReportItem struct for EmbyReportsApiModelReportItem
type EmbyReportsApiModelReportItem struct {
	Id *string `json:"Id,omitempty"`
	Name *string `json:"Name,omitempty"`
	Image *string `json:"Image,omitempty"`
	CustomTag *string `json:"CustomTag,omitempty"`
}

// NewEmbyReportsApiModelReportItem instantiates a new EmbyReportsApiModelReportItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbyReportsApiModelReportItem() *EmbyReportsApiModelReportItem {
	this := EmbyReportsApiModelReportItem{}
	return &this
}

// NewEmbyReportsApiModelReportItemWithDefaults instantiates a new EmbyReportsApiModelReportItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbyReportsApiModelReportItemWithDefaults() *EmbyReportsApiModelReportItem {
	this := EmbyReportsApiModelReportItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EmbyReportsApiModelReportItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbyReportsApiModelReportItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EmbyReportsApiModelReportItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EmbyReportsApiModelReportItem) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EmbyReportsApiModelReportItem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbyReportsApiModelReportItem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EmbyReportsApiModelReportItem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EmbyReportsApiModelReportItem) SetName(v string) {
	o.Name = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *EmbyReportsApiModelReportItem) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbyReportsApiModelReportItem) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *EmbyReportsApiModelReportItem) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *EmbyReportsApiModelReportItem) SetImage(v string) {
	o.Image = &v
}

// GetCustomTag returns the CustomTag field value if set, zero value otherwise.
func (o *EmbyReportsApiModelReportItem) GetCustomTag() string {
	if o == nil || IsNil(o.CustomTag) {
		var ret string
		return ret
	}
	return *o.CustomTag
}

// GetCustomTagOk returns a tuple with the CustomTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbyReportsApiModelReportItem) GetCustomTagOk() (*string, bool) {
	if o == nil || IsNil(o.CustomTag) {
		return nil, false
	}
	return o.CustomTag, true
}

// HasCustomTag returns a boolean if a field has been set.
func (o *EmbyReportsApiModelReportItem) HasCustomTag() bool {
	if o != nil && !IsNil(o.CustomTag) {
		return true
	}

	return false
}

// SetCustomTag gets a reference to the given string and assigns it to the CustomTag field.
func (o *EmbyReportsApiModelReportItem) SetCustomTag(v string) {
	o.CustomTag = &v
}

func (o EmbyReportsApiModelReportItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbyReportsApiModelReportItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Image) {
		toSerialize["Image"] = o.Image
	}
	if !IsNil(o.CustomTag) {
		toSerialize["CustomTag"] = o.CustomTag
	}
	return toSerialize, nil
}

type NullableEmbyReportsApiModelReportItem struct {
	value *EmbyReportsApiModelReportItem
	isSet bool
}

func (v NullableEmbyReportsApiModelReportItem) Get() *EmbyReportsApiModelReportItem {
	return v.value
}

func (v *NullableEmbyReportsApiModelReportItem) Set(val *EmbyReportsApiModelReportItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbyReportsApiModelReportItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbyReportsApiModelReportItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbyReportsApiModelReportItem(val *EmbyReportsApiModelReportItem) *NullableEmbyReportsApiModelReportItem {
	return &NullableEmbyReportsApiModelReportItem{value: val, isSet: true}
}

func (v NullableEmbyReportsApiModelReportItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbyReportsApiModelReportItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


