/*
Emby Server API

Explore the Emby Server API

API version: 4.1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ConfigurationUserConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationUserConfiguration{}

// ConfigurationUserConfiguration struct for ConfigurationUserConfiguration
type ConfigurationUserConfiguration struct {
	AudioLanguagePreference *string `json:"AudioLanguagePreference,omitempty"`
	PlayDefaultAudioTrack *bool `json:"PlayDefaultAudioTrack,omitempty"`
	SubtitleLanguagePreference *string `json:"SubtitleLanguagePreference,omitempty"`
	DisplayMissingEpisodes *bool `json:"DisplayMissingEpisodes,omitempty"`
	GroupedFolders []string `json:"GroupedFolders,omitempty"`
	SubtitleMode *string `json:"SubtitleMode,omitempty"`
	DisplayCollectionsView *bool `json:"DisplayCollectionsView,omitempty"`
	EnableLocalPassword *bool `json:"EnableLocalPassword,omitempty"`
	OrderedViews []string `json:"OrderedViews,omitempty"`
	LatestItemsExcludes []string `json:"LatestItemsExcludes,omitempty"`
	MyMediaExcludes []string `json:"MyMediaExcludes,omitempty"`
	HidePlayedInLatest *bool `json:"HidePlayedInLatest,omitempty"`
	RememberAudioSelections *bool `json:"RememberAudioSelections,omitempty"`
	RememberSubtitleSelections *bool `json:"RememberSubtitleSelections,omitempty"`
	EnableNextEpisodeAutoPlay *bool `json:"EnableNextEpisodeAutoPlay,omitempty"`
}

// NewConfigurationUserConfiguration instantiates a new ConfigurationUserConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationUserConfiguration() *ConfigurationUserConfiguration {
	this := ConfigurationUserConfiguration{}
	return &this
}

// NewConfigurationUserConfigurationWithDefaults instantiates a new ConfigurationUserConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationUserConfigurationWithDefaults() *ConfigurationUserConfiguration {
	this := ConfigurationUserConfiguration{}
	return &this
}

// GetAudioLanguagePreference returns the AudioLanguagePreference field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetAudioLanguagePreference() string {
	if o == nil || IsNil(o.AudioLanguagePreference) {
		var ret string
		return ret
	}
	return *o.AudioLanguagePreference
}

// GetAudioLanguagePreferenceOk returns a tuple with the AudioLanguagePreference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetAudioLanguagePreferenceOk() (*string, bool) {
	if o == nil || IsNil(o.AudioLanguagePreference) {
		return nil, false
	}
	return o.AudioLanguagePreference, true
}

// HasAudioLanguagePreference returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasAudioLanguagePreference() bool {
	if o != nil && !IsNil(o.AudioLanguagePreference) {
		return true
	}

	return false
}

// SetAudioLanguagePreference gets a reference to the given string and assigns it to the AudioLanguagePreference field.
func (o *ConfigurationUserConfiguration) SetAudioLanguagePreference(v string) {
	o.AudioLanguagePreference = &v
}

// GetPlayDefaultAudioTrack returns the PlayDefaultAudioTrack field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetPlayDefaultAudioTrack() bool {
	if o == nil || IsNil(o.PlayDefaultAudioTrack) {
		var ret bool
		return ret
	}
	return *o.PlayDefaultAudioTrack
}

// GetPlayDefaultAudioTrackOk returns a tuple with the PlayDefaultAudioTrack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetPlayDefaultAudioTrackOk() (*bool, bool) {
	if o == nil || IsNil(o.PlayDefaultAudioTrack) {
		return nil, false
	}
	return o.PlayDefaultAudioTrack, true
}

// HasPlayDefaultAudioTrack returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasPlayDefaultAudioTrack() bool {
	if o != nil && !IsNil(o.PlayDefaultAudioTrack) {
		return true
	}

	return false
}

// SetPlayDefaultAudioTrack gets a reference to the given bool and assigns it to the PlayDefaultAudioTrack field.
func (o *ConfigurationUserConfiguration) SetPlayDefaultAudioTrack(v bool) {
	o.PlayDefaultAudioTrack = &v
}

// GetSubtitleLanguagePreference returns the SubtitleLanguagePreference field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetSubtitleLanguagePreference() string {
	if o == nil || IsNil(o.SubtitleLanguagePreference) {
		var ret string
		return ret
	}
	return *o.SubtitleLanguagePreference
}

// GetSubtitleLanguagePreferenceOk returns a tuple with the SubtitleLanguagePreference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetSubtitleLanguagePreferenceOk() (*string, bool) {
	if o == nil || IsNil(o.SubtitleLanguagePreference) {
		return nil, false
	}
	return o.SubtitleLanguagePreference, true
}

// HasSubtitleLanguagePreference returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasSubtitleLanguagePreference() bool {
	if o != nil && !IsNil(o.SubtitleLanguagePreference) {
		return true
	}

	return false
}

// SetSubtitleLanguagePreference gets a reference to the given string and assigns it to the SubtitleLanguagePreference field.
func (o *ConfigurationUserConfiguration) SetSubtitleLanguagePreference(v string) {
	o.SubtitleLanguagePreference = &v
}

// GetDisplayMissingEpisodes returns the DisplayMissingEpisodes field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetDisplayMissingEpisodes() bool {
	if o == nil || IsNil(o.DisplayMissingEpisodes) {
		var ret bool
		return ret
	}
	return *o.DisplayMissingEpisodes
}

// GetDisplayMissingEpisodesOk returns a tuple with the DisplayMissingEpisodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetDisplayMissingEpisodesOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplayMissingEpisodes) {
		return nil, false
	}
	return o.DisplayMissingEpisodes, true
}

// HasDisplayMissingEpisodes returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasDisplayMissingEpisodes() bool {
	if o != nil && !IsNil(o.DisplayMissingEpisodes) {
		return true
	}

	return false
}

// SetDisplayMissingEpisodes gets a reference to the given bool and assigns it to the DisplayMissingEpisodes field.
func (o *ConfigurationUserConfiguration) SetDisplayMissingEpisodes(v bool) {
	o.DisplayMissingEpisodes = &v
}

// GetGroupedFolders returns the GroupedFolders field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetGroupedFolders() []string {
	if o == nil || IsNil(o.GroupedFolders) {
		var ret []string
		return ret
	}
	return o.GroupedFolders
}

// GetGroupedFoldersOk returns a tuple with the GroupedFolders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetGroupedFoldersOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupedFolders) {
		return nil, false
	}
	return o.GroupedFolders, true
}

// HasGroupedFolders returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasGroupedFolders() bool {
	if o != nil && !IsNil(o.GroupedFolders) {
		return true
	}

	return false
}

// SetGroupedFolders gets a reference to the given []string and assigns it to the GroupedFolders field.
func (o *ConfigurationUserConfiguration) SetGroupedFolders(v []string) {
	o.GroupedFolders = v
}

// GetSubtitleMode returns the SubtitleMode field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetSubtitleMode() string {
	if o == nil || IsNil(o.SubtitleMode) {
		var ret string
		return ret
	}
	return *o.SubtitleMode
}

// GetSubtitleModeOk returns a tuple with the SubtitleMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetSubtitleModeOk() (*string, bool) {
	if o == nil || IsNil(o.SubtitleMode) {
		return nil, false
	}
	return o.SubtitleMode, true
}

// HasSubtitleMode returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasSubtitleMode() bool {
	if o != nil && !IsNil(o.SubtitleMode) {
		return true
	}

	return false
}

// SetSubtitleMode gets a reference to the given string and assigns it to the SubtitleMode field.
func (o *ConfigurationUserConfiguration) SetSubtitleMode(v string) {
	o.SubtitleMode = &v
}

// GetDisplayCollectionsView returns the DisplayCollectionsView field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetDisplayCollectionsView() bool {
	if o == nil || IsNil(o.DisplayCollectionsView) {
		var ret bool
		return ret
	}
	return *o.DisplayCollectionsView
}

// GetDisplayCollectionsViewOk returns a tuple with the DisplayCollectionsView field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetDisplayCollectionsViewOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplayCollectionsView) {
		return nil, false
	}
	return o.DisplayCollectionsView, true
}

// HasDisplayCollectionsView returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasDisplayCollectionsView() bool {
	if o != nil && !IsNil(o.DisplayCollectionsView) {
		return true
	}

	return false
}

// SetDisplayCollectionsView gets a reference to the given bool and assigns it to the DisplayCollectionsView field.
func (o *ConfigurationUserConfiguration) SetDisplayCollectionsView(v bool) {
	o.DisplayCollectionsView = &v
}

// GetEnableLocalPassword returns the EnableLocalPassword field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetEnableLocalPassword() bool {
	if o == nil || IsNil(o.EnableLocalPassword) {
		var ret bool
		return ret
	}
	return *o.EnableLocalPassword
}

// GetEnableLocalPasswordOk returns a tuple with the EnableLocalPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetEnableLocalPasswordOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableLocalPassword) {
		return nil, false
	}
	return o.EnableLocalPassword, true
}

// HasEnableLocalPassword returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasEnableLocalPassword() bool {
	if o != nil && !IsNil(o.EnableLocalPassword) {
		return true
	}

	return false
}

// SetEnableLocalPassword gets a reference to the given bool and assigns it to the EnableLocalPassword field.
func (o *ConfigurationUserConfiguration) SetEnableLocalPassword(v bool) {
	o.EnableLocalPassword = &v
}

// GetOrderedViews returns the OrderedViews field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetOrderedViews() []string {
	if o == nil || IsNil(o.OrderedViews) {
		var ret []string
		return ret
	}
	return o.OrderedViews
}

// GetOrderedViewsOk returns a tuple with the OrderedViews field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetOrderedViewsOk() ([]string, bool) {
	if o == nil || IsNil(o.OrderedViews) {
		return nil, false
	}
	return o.OrderedViews, true
}

// HasOrderedViews returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasOrderedViews() bool {
	if o != nil && !IsNil(o.OrderedViews) {
		return true
	}

	return false
}

// SetOrderedViews gets a reference to the given []string and assigns it to the OrderedViews field.
func (o *ConfigurationUserConfiguration) SetOrderedViews(v []string) {
	o.OrderedViews = v
}

// GetLatestItemsExcludes returns the LatestItemsExcludes field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetLatestItemsExcludes() []string {
	if o == nil || IsNil(o.LatestItemsExcludes) {
		var ret []string
		return ret
	}
	return o.LatestItemsExcludes
}

// GetLatestItemsExcludesOk returns a tuple with the LatestItemsExcludes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetLatestItemsExcludesOk() ([]string, bool) {
	if o == nil || IsNil(o.LatestItemsExcludes) {
		return nil, false
	}
	return o.LatestItemsExcludes, true
}

// HasLatestItemsExcludes returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasLatestItemsExcludes() bool {
	if o != nil && !IsNil(o.LatestItemsExcludes) {
		return true
	}

	return false
}

// SetLatestItemsExcludes gets a reference to the given []string and assigns it to the LatestItemsExcludes field.
func (o *ConfigurationUserConfiguration) SetLatestItemsExcludes(v []string) {
	o.LatestItemsExcludes = v
}

// GetMyMediaExcludes returns the MyMediaExcludes field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetMyMediaExcludes() []string {
	if o == nil || IsNil(o.MyMediaExcludes) {
		var ret []string
		return ret
	}
	return o.MyMediaExcludes
}

// GetMyMediaExcludesOk returns a tuple with the MyMediaExcludes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetMyMediaExcludesOk() ([]string, bool) {
	if o == nil || IsNil(o.MyMediaExcludes) {
		return nil, false
	}
	return o.MyMediaExcludes, true
}

// HasMyMediaExcludes returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasMyMediaExcludes() bool {
	if o != nil && !IsNil(o.MyMediaExcludes) {
		return true
	}

	return false
}

// SetMyMediaExcludes gets a reference to the given []string and assigns it to the MyMediaExcludes field.
func (o *ConfigurationUserConfiguration) SetMyMediaExcludes(v []string) {
	o.MyMediaExcludes = v
}

// GetHidePlayedInLatest returns the HidePlayedInLatest field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetHidePlayedInLatest() bool {
	if o == nil || IsNil(o.HidePlayedInLatest) {
		var ret bool
		return ret
	}
	return *o.HidePlayedInLatest
}

// GetHidePlayedInLatestOk returns a tuple with the HidePlayedInLatest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetHidePlayedInLatestOk() (*bool, bool) {
	if o == nil || IsNil(o.HidePlayedInLatest) {
		return nil, false
	}
	return o.HidePlayedInLatest, true
}

// HasHidePlayedInLatest returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasHidePlayedInLatest() bool {
	if o != nil && !IsNil(o.HidePlayedInLatest) {
		return true
	}

	return false
}

// SetHidePlayedInLatest gets a reference to the given bool and assigns it to the HidePlayedInLatest field.
func (o *ConfigurationUserConfiguration) SetHidePlayedInLatest(v bool) {
	o.HidePlayedInLatest = &v
}

// GetRememberAudioSelections returns the RememberAudioSelections field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetRememberAudioSelections() bool {
	if o == nil || IsNil(o.RememberAudioSelections) {
		var ret bool
		return ret
	}
	return *o.RememberAudioSelections
}

// GetRememberAudioSelectionsOk returns a tuple with the RememberAudioSelections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetRememberAudioSelectionsOk() (*bool, bool) {
	if o == nil || IsNil(o.RememberAudioSelections) {
		return nil, false
	}
	return o.RememberAudioSelections, true
}

// HasRememberAudioSelections returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasRememberAudioSelections() bool {
	if o != nil && !IsNil(o.RememberAudioSelections) {
		return true
	}

	return false
}

// SetRememberAudioSelections gets a reference to the given bool and assigns it to the RememberAudioSelections field.
func (o *ConfigurationUserConfiguration) SetRememberAudioSelections(v bool) {
	o.RememberAudioSelections = &v
}

// GetRememberSubtitleSelections returns the RememberSubtitleSelections field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetRememberSubtitleSelections() bool {
	if o == nil || IsNil(o.RememberSubtitleSelections) {
		var ret bool
		return ret
	}
	return *o.RememberSubtitleSelections
}

// GetRememberSubtitleSelectionsOk returns a tuple with the RememberSubtitleSelections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetRememberSubtitleSelectionsOk() (*bool, bool) {
	if o == nil || IsNil(o.RememberSubtitleSelections) {
		return nil, false
	}
	return o.RememberSubtitleSelections, true
}

// HasRememberSubtitleSelections returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasRememberSubtitleSelections() bool {
	if o != nil && !IsNil(o.RememberSubtitleSelections) {
		return true
	}

	return false
}

// SetRememberSubtitleSelections gets a reference to the given bool and assigns it to the RememberSubtitleSelections field.
func (o *ConfigurationUserConfiguration) SetRememberSubtitleSelections(v bool) {
	o.RememberSubtitleSelections = &v
}

// GetEnableNextEpisodeAutoPlay returns the EnableNextEpisodeAutoPlay field value if set, zero value otherwise.
func (o *ConfigurationUserConfiguration) GetEnableNextEpisodeAutoPlay() bool {
	if o == nil || IsNil(o.EnableNextEpisodeAutoPlay) {
		var ret bool
		return ret
	}
	return *o.EnableNextEpisodeAutoPlay
}

// GetEnableNextEpisodeAutoPlayOk returns a tuple with the EnableNextEpisodeAutoPlay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUserConfiguration) GetEnableNextEpisodeAutoPlayOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableNextEpisodeAutoPlay) {
		return nil, false
	}
	return o.EnableNextEpisodeAutoPlay, true
}

// HasEnableNextEpisodeAutoPlay returns a boolean if a field has been set.
func (o *ConfigurationUserConfiguration) HasEnableNextEpisodeAutoPlay() bool {
	if o != nil && !IsNil(o.EnableNextEpisodeAutoPlay) {
		return true
	}

	return false
}

// SetEnableNextEpisodeAutoPlay gets a reference to the given bool and assigns it to the EnableNextEpisodeAutoPlay field.
func (o *ConfigurationUserConfiguration) SetEnableNextEpisodeAutoPlay(v bool) {
	o.EnableNextEpisodeAutoPlay = &v
}

func (o ConfigurationUserConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationUserConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AudioLanguagePreference) {
		toSerialize["AudioLanguagePreference"] = o.AudioLanguagePreference
	}
	if !IsNil(o.PlayDefaultAudioTrack) {
		toSerialize["PlayDefaultAudioTrack"] = o.PlayDefaultAudioTrack
	}
	if !IsNil(o.SubtitleLanguagePreference) {
		toSerialize["SubtitleLanguagePreference"] = o.SubtitleLanguagePreference
	}
	if !IsNil(o.DisplayMissingEpisodes) {
		toSerialize["DisplayMissingEpisodes"] = o.DisplayMissingEpisodes
	}
	if !IsNil(o.GroupedFolders) {
		toSerialize["GroupedFolders"] = o.GroupedFolders
	}
	if !IsNil(o.SubtitleMode) {
		toSerialize["SubtitleMode"] = o.SubtitleMode
	}
	if !IsNil(o.DisplayCollectionsView) {
		toSerialize["DisplayCollectionsView"] = o.DisplayCollectionsView
	}
	if !IsNil(o.EnableLocalPassword) {
		toSerialize["EnableLocalPassword"] = o.EnableLocalPassword
	}
	if !IsNil(o.OrderedViews) {
		toSerialize["OrderedViews"] = o.OrderedViews
	}
	if !IsNil(o.LatestItemsExcludes) {
		toSerialize["LatestItemsExcludes"] = o.LatestItemsExcludes
	}
	if !IsNil(o.MyMediaExcludes) {
		toSerialize["MyMediaExcludes"] = o.MyMediaExcludes
	}
	if !IsNil(o.HidePlayedInLatest) {
		toSerialize["HidePlayedInLatest"] = o.HidePlayedInLatest
	}
	if !IsNil(o.RememberAudioSelections) {
		toSerialize["RememberAudioSelections"] = o.RememberAudioSelections
	}
	if !IsNil(o.RememberSubtitleSelections) {
		toSerialize["RememberSubtitleSelections"] = o.RememberSubtitleSelections
	}
	if !IsNil(o.EnableNextEpisodeAutoPlay) {
		toSerialize["EnableNextEpisodeAutoPlay"] = o.EnableNextEpisodeAutoPlay
	}
	return toSerialize, nil
}

type NullableConfigurationUserConfiguration struct {
	value *ConfigurationUserConfiguration
	isSet bool
}

func (v NullableConfigurationUserConfiguration) Get() *ConfigurationUserConfiguration {
	return v.value
}

func (v *NullableConfigurationUserConfiguration) Set(val *ConfigurationUserConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationUserConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationUserConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationUserConfiguration(val *ConfigurationUserConfiguration) *NullableConfigurationUserConfiguration {
	return &NullableConfigurationUserConfiguration{value: val, isSet: true}
}

func (v NullableConfigurationUserConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationUserConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


